services:
  ###############################################################################
  # Redis
  ###############################################################################
  redis:
    image: redis:7.4-bookworm
    environment:
      REDIS_PORT: 6379
    expose:
      - '6379'
    volumes:
      - ./data/redis:/data
    command: [
        'sh',
        '-c',
        'docker-entrypoint.sh --requirepass ${REDIS_PASSWORD:-redis_password} --loglevel warning'
      ] # Change password in production
    networks:
      - net
  ###############################################################################
  # Mongo
  ###############################################################################
  mongo:
    image: mongo:7
    environment:
      MONGO_PORT: 27017
    command: --quiet --logpath /dev/null
    expose:
      - '27017'
    volumes:
      - ./data/mongodb:/data/db
      - ./backup:/backup
    networks:
      - net
  ###############################################################################
  # Reverse Proxy
  ###############################################################################
  reverse-proxy:
    image: caddy:latest
    profiles:
      - ''
    command: caddy reverse-proxy --from ${APP_PROTOCOL:-http}://$APP_DOMAIN${APP_PORT:+:}$APP_PORT --to gateway:8080
    ports:
      - ${APP_PORT:-80}:${APP_PORT:-80}
      - 443:443
    networks:
      - net
  ###############################################################################
  # Gateway
  ###############################################################################
  gateway:
    restart: unless-stopped
    image: 'ghcr.io/microjobboard/microjobboard/gateway:${MRE_VERSION:-latest}'
    environment:
      NODE_ENV: production
      LOGGER_LEVEL: info
      PORT: 8080
      EXPOSE_FRONTENDS: 'true'
      AUTHENTICATOR_URL: http://authenticator:8000
      API_URL: http://api:8200/api/v2
      PDFGENERATOR_URL: http://pdfgenerator:8300/pdfgenerator
      EMAILER_URL: http://emailer:8400/emailer
      EMPLOYER_FRONTEND_URL: http://EMPLOYER-frontend:8180
      EMPLOYER_BASE_PATH: /EMPLOYER
      WORKER_FRONTEND_URL: http://worker-frontend:8190
      WORKER_BASE_PATH: /worker
      APP_DOMAIN: ${APP_DOMAIN:-localhost}${APP_PORT:+:}$APP_PORT
      CORS_ENABLED: 'true'
      WORKERAPI_URL: http://WORKERapi:8250/WORKERapi
    ports:
      - '8080:8080'
    # healthcheck:
    #   test:
    #     [
    #       'CMD-SHELL',
    #       'wget --no-verbose --tries=1 --spider ${APP_PROTOCOL:-http}://${APP_DOMAIN:-localhost}${APP_PORT:+:}$APP_PORT/health/noUI || exit 1'
    #     ]
    #   interval: 1s
    #   timeout: 2s
    #   retries: 20
    #   start_period: 15s
    networks:
      - net
    depends_on:
      authenticator:
        condition: service_started
      api:
        condition: service_started
      WORKERapi:
        condition: service_started
      pdfgenerator:
        condition: service_started
      emailer:
        condition: service_started
  ###############################################################################
  # Authenticator
  ###############################################################################
  authenticator:
    restart: unless-stopped
    image: 'ghcr.io/microjobboard/microjobboard/authenticator:${MRE_VERSION:-latest}'
    environment:
      NODE_ENV: production
      PORT: 8000
      LOGGER_LEVEL: info
      REDIS_URL: redis://redis
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis_password} # Change password in production
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET:-access_token_secret} # Change secret in production
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET:-refresh_token_secret} # Change secret in production
      RESET_TOKEN_SECRET: ${RESET_TOKEN_SECRET:-reset_token_secret} # Change secret in production
      APPCREDZ_TOKEN_SECRET: ${APPCREDZ_TOKEN_SECRET:-appcredz_token_secret} # Change secret in production
      MONGO_URL: ${MONGO_URL:-mongodb://mongo/mredb}
      EMAILER_URL: http://emailer:8400/emailer
      SIGNUP: 'true'
      APP_DOMAIN: ${APP_DOMAIN:-localhost} # do not pass APP_PORT here
      APP_PROTOCOL: ${APP_PROTOCOL:-http}
    expose:
      - '8000'
    networks:
      - net
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_started
      emailer:
        condition: service_started
  ###############################################################################
  # api
  ###############################################################################
  api:
    restart: unless-stopped
    image: 'ghcr.io/microjobboard/microjobboard/api:${MRE_VERSION:-latest}'
    volumes:
      - ./backup:/usr/app/backup
    environment:
      NODE_ENV: production
      PORT: 8200
      LOGGER_LEVEL: info
      MONGO_URL: ${MONGO_URL:-mongodb://mongo/mredb}
      EMAILER_URL: http://emailer:8400/emailer
      PDFGENERATOR_URL: http://pdfgenerator:8300/pdfgenerator
      RESTORE_DB: 'false'
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET:-access_token_secret} # Change secret in production
      CIPHER_KEY: ${CIPHER_KEY:-cipher_key} # Change key in production
      CIPHER_IV_KEY: ${CIPHER_IV_KEY:-cipher_iv_key} # Change key in production
    expose:
      - '8200'
    networks:
      - net
    depends_on:
      mongo:
        condition: service_started
      emailer:
        condition: service_started
      pdfgenerator:
        condition: service_started
  ###############################################################################
  # EMPLOYER frontend
  ###############################################################################
  EMPLOYER-frontend:
    restart: unless-stopped
    image: 'ghcr.io/microjobboard/microjobboard/EMPLOYER-frontend:${MRE_VERSION:-latest}'
    environment:
      BASE_PATH: /EMPLOYER
      PORT: 8180
      DOCKER_GATEWAY_URL: http://gateway:8080
      CORS_ENABLED: 'true'
      GATEWAY_URL: ${APP_PROTOCOL:-http}://${APP_DOMAIN:-localhost}${APP_PORT:+:}$APP_PORT
      NODE_ENV: production
      SIGNUP: 'true'
    expose:
      - '8180'
    networks:
      - net
    depends_on:
      gateway:
        condition: service_started
  ###############################################################################
  # WORKER frontend
  ###############################################################################
  worker-frontend:
    restart: unless-stopped
    image: 'ghcr.io/microjobboard/microjobboard/worker-frontend:${MRE_VERSION:-latest}'
    environment:
      BASE_PATH: /worker
      PORT: 8190
      DOCKER_GATEWAY_URL: http://gateway:8080
      CORS_ENABLED: 'true'
      GATEWAY_URL: ${APP_PROTOCOL:-http}://${APP_DOMAIN:-localhost}${APP_PORT:+:}$APP_PORT
      NODE_ENV: production
    expose:
      - '8190'
    networks:
      - net
    depends_on:
      gateway:
        condition: service_started
###############################################################################
# microservices network
###############################################################################
networks:
  net:
    driver: bridge
